title: EnviroEm
theme: minima
author: Emily Cassidy
email: emilyscassidy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Emily Cassidy is an environmental scientist and science writer. This is Emily's personal blog.
  
# social links
twitter_username: EnviroEm
github_username:  emilyscassidy

show_excerpts: true 
